---
driver:
  name: vagrant
  require_chef_omnibus: 17.10.3
  box_check_update: true
  network:
    - ['forwarded_port', {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero
  product_version: 17.10.3
  chef_license: accept-no-persist

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[kloudspeaker]
      - recipe[kloudspeaker::webdav]
    attributes:
      kloudspeaker:
        nginx:
          ordered_directives:
            - ['allow', 'all']
            - ['deny', ['127.0.0.254', '127.0.0.253']]
          location:
            directives:
              allow: all
            ordered_directives:
              - ['deny', ['127.0.0.252', '127.0.0.251']]
      mariadb:
        install:
          prefer_os_package: true
